theme: jekyll-theme-minimal
title: SADE - Sistema de Avaliação e Desempenho Educacional
description: Plataforma moderna desenvolvida em Django para análise de desempenho educacional
url: https://pauloheg33.github.io/sade/
author: Paulo Henrique
show_downloads: true
google_analytics: # Adicione seu ID do Google Analytics se necessário

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

# Configurações SEO
lang: pt-BR
locale: pt_BR

# Social
github_username: pauloheg33
linkedin_username: pauloheg33

# Configuração do repositório
repository: pauloheg33/sade
