name: SADE
description: Sistema de Avaliação e Desempenho Escolar - Secretaria da Educação de Ararendá
url: https://pauloheg33.github.io/sade
baseurl: /sade

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - README.md
  - .git/
  - .github/
  - process_data.py
  - .venv/
  - __pycache__/
  - "*.pyc"

include:
  - .htaccess

defaults:
  - scope:
      path: ""
    values:
      layout: default
