# Generated by Django 5.2.4 on 2025-07-25 02:13

import dashboard.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Escola",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Gabarito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome identificador do gabarito", max_length=255
                    ),
                ),
                (
                    "ano_escolar",
                    models.CharField(
                        choices=[
                            ("1ano", "1º Ano"),
                            ("2ano", "2º Ano"),
                            ("3ano", "3º Ano"),
                            ("4ano", "4º Ano"),
                            ("5ano", "5º Ano"),
                            ("6ano", "6º Ano"),
                            ("7ano", "7º Ano"),
                            ("8ano", "8º Ano"),
                            ("9ano", "9º Ano"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "arquivo_csv",
                    models.FileField(
                        help_text="Arquivo CSV com as respostas corretas",
                        upload_to=dashboard.models.gabarito_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(["csv"])
                        ],
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, help_text="Gabarito ativo para uso"
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gabarito",
                "verbose_name_plural": "Gabaritos",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                (
                    "resposta_correta",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "habilidade",
                    models.CharField(
                        blank=True,
                        help_text="Habilidade avaliada (opcional)",
                        max_length=255,
                    ),
                ),
                (
                    "gabarito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.gabarito",
                    ),
                ),
            ],
            options={
                "ordering": ["numero"],
                "unique_together": {("gabarito", "numero")},
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "ano",
                    models.CharField(
                        choices=[
                            ("1ano", "1º Ano"),
                            ("2ano", "2º Ano"),
                            ("3ano", "3º Ano"),
                            ("4ano", "4º Ano"),
                            ("5ano", "5º Ano"),
                            ("6ano", "6º Ano"),
                            ("7ano", "7º Ano"),
                            ("8ano", "8º Ano"),
                            ("9ano", "9º Ano"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.escola",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.turma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadResultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome identificador do upload", max_length=255
                    ),
                ),
                (
                    "arquivo_csv",
                    models.FileField(
                        help_text="Arquivo CSV com os resultados dos alunos",
                        upload_to=dashboard.models.resultado_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(["csv"])
                        ],
                    ),
                ),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                ("processado", models.BooleanField(default=False)),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload de Resultado",
                "verbose_name_plural": "Uploads de Resultados",
                "ordering": ["-data_upload"],
            },
        ),
        migrations.CreateModel(
            name="AnaliseDesempenho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_alunos", models.PositiveIntegerField()),
                ("total_questoes", models.PositiveIntegerField()),
                (
                    "media_geral",
                    models.FloatField(help_text="Média geral de acertos (%)"),
                ),
                ("data_analise", models.DateTimeField(auto_now_add=True)),
                (
                    "upload_resultado",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.uploadresultado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise de Desempenho",
                "verbose_name_plural": "Análises de Desempenho",
            },
        ),
        migrations.CreateModel(
            name="Resposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resposta_aluno",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("", "Não respondida"),
                        ],
                        max_length=1,
                    ),
                ),
                ("correta", models.BooleanField()),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.aluno",
                    ),
                ),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.questao",
                    ),
                ),
                (
                    "upload_resultado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.uploadresultado",
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno", "questao")},
            },
        ),
    ]
